services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postchain
      - POSTGRES_PASSWORD=postchain
      - POSTGRES_DB=postchain
      - LANG=C.UTF-8
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C.UTF-8
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
